---
title: "MHHS Scoring"
output: html_notebook
---

```{r load libraries}
library(psych)
library(tidyverse)
library(apaTables)
library(tableone)
library(dplyr)

```

```{r clean qualtrics headings}
#columnNames<-read.csv("../../01-RawData/MHHS_01182023.csv",header=FALSE)[1,]

#qual_data<-read.csv("../../01-RawData/MHHS_01182023.csv",header=FALSE,col.names = columnNames)[-c(1:3),]

# write a new version that can be reimported with the proper column classes
#write.csv(qual_data,"../../03-ProcessData/MHHS_01182023_cleanheader.csv",row.names=FALSE)
```

```{r load data}

mhhs_data<-read.csv("../../03-ProcessData/MHHS_01182023_cleanheader.csv")

```

```{r demographics}

# Know the range of possible answers for each factor and make sure to include NA

mhhs_demotbl<-mhhs_data %>% select(Race_Ethn2,BIC_1,LANG_1,EDUC_Par,EDUC_Self,GENDER,SEXOR,MILIT) %>% 
mutate(
Race_Ethn2=factor(Race_Ethn2,levels=c(NA,1,2,3,4,5,6,7),labels=c("Not answered","White","Black","Hispanic","Asian","AmerIndian","PacificIslander","Multiracial"),exclude=NULL), 
BIC_1=factor(BIC_1, levels=c(NA,1,2,3),labels=c("Not answered","NotBicultural","Bicultural")), 
LANG_1=factor(LANG_1, levels=c(NA,1,2,3),labels=c("Not Answered","English at Home","Additional Language at Home")), 
EDUC_Par=factor(EDUC_Par,levels=c(NA,1,2,3,4,5,6,7),labels = c("Not answered","<High School","High School","Some college","Associates","Bachelors","Masters","Doctoral/Professional"),exclude = NULL),
EDUC_Self=factor(EDUC_Self,levels=c(NA,1,2,3,4,5,6,7),labels = c("Not answered","<High School","High School","Some college","Associates","Bachelors","Masters","Doctoral/Professional"),exclude=NULL), 
GENDER=factor(GENDER,levels=c(NA,1,2,3,4,5,6,7),labels=c("Not answered","cis-woman","cis-man","trans woman","trans man","non-binary","self-id","prefer not to respond"),exclude=NULL), 
SexualOrientation=factor(SEXOR, levels=c(NA,1,2,3,4,5,6,7,8), labels = c("Not Answered","Straight","Bisexual","Gay","Lesbian","Queer","Questioning","Self-ID","Prefer not to respond"),exclude = NULL), 
MilitaryService=factor(MILIT,levels=c(NA,1,2,3,4,5,6,7,8),labels=c("Not answered","Never Served","Active Duty","National Guard","Military Spouse","Military Dependent","Veteran","Other","Prefer not to respond"),exclude=NULL)) %>% 
select(-MILIT,-SEXOR)

CreateTableOne(data=mhhs_tbl)
```
```{r PROMIS}
promis_global<-mhhs_data %>% select(contains("PROMIS"))

#score items so that higher scores reflect better functioning 

#check if survey coded Excellent as 1 or as 5. Qualtrics will often reverse them.

# pain item: 5=0, 4=1:3, 3=4:6, 2=7:9, 1=10

as.numeric(promis_global)

promis_global %>% mutate(across(PROMIS_Global1_1:PROMIS_Global1_7,~6-.))

key-promis<-make.keys(nvars=10,PH=c(3,6,-7,-8),MH=c(2,4,5,-10))
```

