```{r load libraries}
library(psych)
library(tidyverse)
library(apaTables)
library(tableone)
library(dplyr)
library(qualtRics)
library(kutils)
library(pmr)


```

```{r load data}

mhhs_data<-read.csv("../../03-Data/04-ProcessedData/MHHS_01182023_cleanheader.csv")

str(mhhs_data)
```

```{r transform matrix}
g10<-mhhs_data %>% select(GHSQ_RankPers_1:GHSQ_RankPers_9)
g10<-g10[complete.cases(g10),]

rankg10<-rankagg(g10)
destat(rankg10)


rankagg(ghsql[complete.cases(ghsql),1:10])
#Experience: 1=0-5, 2-6-10, 3=11-15, 4-16-20, 5=21+
#Degree: 1=BA/BS, 2=MA/MS, 3=Specialist, 4=PhD
faculty.survey<-Finch_supp_data
faculty.rankings<-data.frame(faculty.survey[,1:6])
faculty.rankings.agg<-rankagg(faculty.rankings)#Experience: 1=0-5, 2-6-10, 3=11-15, 4-16-20, 5=21+
#Degree: 1=BA/BS, 2=MA/MS, 3=Specialist, 4=PhD
faculty.rankings<-data.frame(faculty.survey[,1:6])
faculty.rankings.agg<-rankagg(faculty.rankings)

destat(faculty.rankings.agg)

mdpref(faculty.rankings.agg,rank.vector = T)
```

